parameters:
    ezpublish.elasticsearch.connection_parameter_factory.class: eZ\Bundle\EzPublishElasticsearchSearchEngineBundle\ApiLoader\ConnectionParameterFactory
    ezpublish.elasticsearch.engine_factory.class: eZ\Bundle\EzPublishElasticsearchSearchEngineBundle\ApiLoader\ElasticsearchEngineFactory
    ez_search_engine_elasticsearch.default_connection: ~

services:
    ezpublish.elasticsearch.connection_parameter_factory:
        class: %ezpublish.elasticsearch.connection_parameter_factory.class%
        arguments:
            - @ezpublish.api.repository_configuration_provider
            - 'ez_search_engine_elasticsearch'
            - 'default_connection'
            - 'ezpublish.search.elasticsearch.connection'
        calls:
            - [setContainer, [@service_container]]

    ezpublish.elasticsearch.engine_factory:
        class: %ezpublish.elasticsearch.engine_factory.class%
        arguments:
            - @ezpublish.api.repository_configuration_provider
            - %ez_search_engine_elasticsearch.default_connection%
            - %ezpublish.spi.search.elasticsearch.class%
        calls:
            - [setContainer, [@service_container]]
